version: '3'

services:
  inaina:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./.deploy/nginx/production.nginx:/etc/nginx/conf.d/default.conf
      - ./.deploy/certbot/conf:/etc/letsencrypt
      - ./.deploy/certbot/www:/var/www/certbot
      - static:/srv/.static
    depends_on:
      - django
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off; worker_processes 1;\"'"
    networks:
      - default
      - proxy

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - default

  django:
    &django
    build:
      context: .
      dockerfile: Dockerfile.deploy
      args:
        requirements: requirements.txt
    environment:
      - DJANGO_SETTINGS_MODULE
      - AWS_S3_ACCESS_KEY_ID
      - AWS_S3_SECRET_ACCESS_KEY
    volumes:
      - static:/srv/.static
    command: bash -c '
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      gunicorn -c /srv/.deploy/gunicorn/production.py config.wsgi.production'
    networks:
      - default

volumes:
  static:

networks:
  default:
  proxy:
    external: true
