version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./.deploy/nginx/${nginx}:/etc/nginx/conf.d/default.conf
      - static:/srv/.static
    ports:
      - 80:80
      - 443:443

  django:
    &django
    build:
      context: .
      dockerfile: ${dockerfile}
      args:
        requirements: ${requirements}
    environment:
      - DOCKER=1
      - DJANGO_SETTINGS_MODULE
      - AWS_S3_ACCESS_KEY_ID
      - AWS_S3_SECRET_ACCESS_KEY
    volumes:
      - static:/srv/.static
    command: bash -c '
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      gunicorn -c /srv/.deploy/gunicorn/${gunicorn} ${wsgi}'

volumes:
  static: