[tool.poetry]
name = "inaina"
version = "0.1.0"
description = ""
authors = ["이한영 <dev@lhy.kr>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.2.7"
django-extensions = "^2.2.5"
django-storages = "^1.7.2"
django-aws-secrets-manager = "^0.1.2"
boto3 = "^1.10.14"
pillow = "^6.2.1"
psycopg2-binary = "^2.8.4"
gunicorn = "^20.0.0"
sentry-sdk = "^0.13.2"
django-dbbackup = "<3.2"

[tool.poetry.dev-dependencies]
notebook = "^6.0.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
