# Generated by Django 3.2.3 on 2021-05-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photopost",
            name="image_thumbnail",
            field=models.ImageField(blank=True, help_text="없을경우 대표이미지 사용", upload_to="", verbose_name="썸네일이미지"),
        ),
        migrations.AddField(
            model_name="photopost",
            name="image_title",
            field=models.ImageField(blank=True, upload_to="", verbose_name="대표이미지"),
        ),
    ]
