# Generated by Django 3.2.3 on 2021-05-18 06:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_auto_20210514_1747"),
    ]

    operations = [
        migrations.AddField(
            model_name="photopost",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200, verbose_name="부제목"),
        ),
        migrations.AddField(
            model_name="photopost",
            name="subtitle_color",
            field=colorfield.fields.ColorField(default="#444", max_length=18, verbose_name="부제목색상"),
        ),
        migrations.AddField(
            model_name="photopost",
            name="title_color",
            field=colorfield.fields.ColorField(default="#333", max_length=18, verbose_name="제목색상"),
        ),
        migrations.AlterField(
            model_name="photopost",
            name="title",
            field=models.CharField(max_length=60, verbose_name="제목"),
        ),
    ]
