# Generated by Django 3.2.3 on 2021-05-18 06:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_auto_20210518_1533"),
    ]

    operations = [
        migrations.AddField(
            model_name="photopost",
            name="date_color",
            field=colorfield.fields.ColorField(default="#555", max_length=18, verbose_name="날짜색상"),
        ),
    ]
