# Generated by Django 3.2.3 on 2021-05-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_auto_20190630_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
